# Generated by Django 5.2.5 on 2025-08-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Chef', 'Chef'), ('Cashier', 'Cashier'), ('Inventory', 'Inventory')], max_length=50),
        ),
    ]
