# Generated by Django 5.2.5 on 2025-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
