# Generated by Django 5.2.5 on 2025-09-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_recipe_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
