# Generated by Django 5.2.5 on 2025-08-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Dry Storage', 'Dry Storage'), ('Refrigerator', 'Refrigerator'), ('Freezer', 'Freezer'), ('Pantry', 'Pantry')], max_length=100)),
                ('shelf_number', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Spices', 'Spices'), ('Beverages', 'Beverages'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Packaging', 'Packaging')], max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Liters'), ('ml', 'Milliliters'), ('pieces', 'Pieces'), ('boxes', 'Boxes'), ('packets', 'Packets'), ('bags', 'Bags'), ('bottles', 'Bottles'), ('jars', 'Jars')], max_length=20)),
                ('minimum_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
    ]
