# Generated by Django 5.2.5 on 2025-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch_number',
            field=models.CharField(max_length=50),
        ),
    ]
