# Generated by Django 5.2.5 on 2025-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_amount_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maximum_stock_level',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
