# Generated by Django 5.2.5 on 2025-10-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
